version: '3'

services:
  odoo:
    image: odoo:17
    container_name: odoo17
    environment:
      - DB_HOST=host.docker.internal  # 确认这是你本地数据库的IP地址
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=123456
      - DB_NAME=odoo17
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]
    networks:
      - odoo-network

networks:
  odoo-network:
